FROM python:3.8

ENV PIP_ROOT_USER_ACTION=ignore

RUN mkdir pathFinder

COPY ./app /pathFinder/app
COPY ./.env /pathFinder/app

WORKDIR /pathFinder

RUN pip install --upgrade pip
RUN pip install -r app/requirements.txt 